### ISSUE TITLE
Video pre-filter

### ISSUE THREAD

**Issue by dastardlii** [Nootna8/Beats2Fun#12]
It would be nice if the program ran a check of each input video as the first step, excluding any videos that are unsupported (too short, wrong codec, etc...).  Alternatively, you could capture the errors when processing those videos and allow the program to continue despite the failure.

**Comment by Nootna8** [comment]
All input videos should, unless they are corrupt. Corrupt meaning that no video player will be able to open it. An option could be added to skip corrupt videos. Too short would mean that the video is shorter then the shortest clip, currently the video would just now be used.

 General video support item: #1 . Please continue there :)
